### ISSUE TITLE
Unable to apply OverrideAsyncMethod successfully

### ISSUE THREAD

**Issue by SophisticatedConsulting** [postsharp/Metalama#15]
When trying migrate and compile a simplified aspect from PostSharp to Metalama, it appears as if the OverrideAsyncMethod version is not applied to async methods.

The aspect I am trying to migrate here is probably a very common scenario to handle exceptions at the last point of interception.

I am following the example code given here: https://doc.metalama.net/aspects/advising/overriding-methods
When I try to test the sample code in the sandbox ("try online") it generates an error: 

```
Unhandled Exception: Unbreakable.AssemblyGuardException: Type System.Runtime.CompilerServices.AsyncIteratorMethodBuilder is not allowed.
   at Unbreakable.Internal.AssemblyValidator.EnsureAllowed(TypeReference type, String memberName)
   at Unbreakable.Internal.AssemblyValidator.ValidateMemberReference(MemberReference reference)
   at Unbreakable.Internal.AssemblyValidator.ValidateInstructionAndGetPolicy(Instruction instruction, MethodDefinition method)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteMethod(MethodDefinition method, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.ValidateAndRewriteType(TypeDefinition type, RuntimeGuardReferences guard, AssemblyValidator validator, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(AssemblyDefinition assembly, AssemblyGuardSettings settings)
   at Unbreakable.AssemblyGuard.Rewrite(Stream assemblySourceStream, Stream assemblyTargetStream, AssemblyGuardSettings settings)
   at WorkspaceServer.Metalama.UnbreakableCompilationRewriter.RewriteWithToken(Stream input, Stream output) in C:\src\Metalama.Try\WorkspaceServer\Metalama\UnbreakableRewriter.cs:line 50
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.EmitCompilationAsync(Compilation compilation, Package package) in C:\src\Metalama.Try\WorkspaceServer\Servers\Roslyn\RoslynWorkspaceServer.cs:line 346
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.Run(WorkspaceRequest request, Budget budget) in C:\src\Metalama.Try\WorkspaceServer\Servers\Roslyn\RoslynWorkspaceServer.cs:line 325
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.Run(WorkspaceRequest request, Budget budget) in C:\src\Metalama.Try\WorkspaceServer\Servers\WorkspaceServerMultiplexer.cs:line 57
   at MLS.Agent.Controllers.RunController.Run(WorkspaceRequest request, String timeoutInMilliseconds) in C:\src\Metalama.Try\MLS.Agent\Controllers\RunController.cs:line 114
```

Though if I remove the enumerator parts of the code it runs correctly (different issue I guess)

A simplified version of my Aspect is:
```
    public sealed class HandleExceptionAttribute : OverrideMethodAspect
    {
        private string _title;
        private string _message;
        private bool _unexpected;

        public HandleExceptionAttribute(string title, string message, bool unexpected = true)
        {
            _title = title;
            _message = message;
            _unexpected = unexpected;
        }

        public override dynamic? OverrideMethod()
        {
            throw new NotImplementedException("Exception handling only for async methods");
        }

        public override async Task<dynamic?> OverrideAsyncMethod()
        {
            try
            {
                return await meta.ProceedAsync();
            }
            catch (Exception ex)
            {
                IAlertUser? alertUser = meta.This as IAlertUser;
                if (alertUser != null)
                    await alertUser.DisplayAlertAsync(_title, "Exception thrown", alertType: AlertType.FailureAlert);

                // Swallow the exception
                return null;
            }
        }
```

An example of its use is:
```
    [HandleException("Unexpected authentication failure", "Unable to sign out.")]
    private async Task OnSignOutClickedAsync()
    {
        UserContext context = await B2CAuthenticationService.Instance.SignOutAsync();

       // Do other stuff
    }
```
The exception that is reported is:

`error CS4032: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task<Task>'.`

If I try to run metalama diff, I get an exception (so I cannot see what code it generates and tries to compile).

**Comment by prochan2** [comment]
Hello, thank you for reporting these issues.

I've filed the one regarding the sandbox and we'll fix it.

However, the code you've provided builds correctly and the diff feature works in my environment:
Visual Studio 2022 17.1.5
Metalama extension for Visual Studio 0.5.8
Metalama.Framework NuGet package 0.5.13-preview

Is there any difference in your environment? If not, could you please share a complete project reproducing the issue?

**Comment by SophisticatedConsulting** [comment]
Thanks for getting back @prochan2 
I am using: VS 17.1.6
Metalama VS ext 0.5.8
Metalama.Framework was 0.5.11 and is now 0.5.13-preview

Updating the framework fixed the diff issue... and the correct code eventually showed through the diff (after deleting bin/obj, cleaning, rebuilding...)
If I copy the generating code and paste it into the method and remove the aspect then the code builds. However, using the aspect attribute still produces the error: 

`error CS4032: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task<Task<int>>`

I created a test harness: 

1. Created a console project
2. Added a library (based on NetStandard 2.1 - I also tried 2.0 with lang v 8) and added a reference to Metalama.Framework NuGet package 0.5.13-preview
3. Added the following interface and class to the library:
```
using System;
using Metalama.Framework.Aspects;
using System.Threading.Tasks;

namespace ServicePlatform.Aspects
{
    public enum AlertType { FailureAlert, Warning, Success }

    public interface IAlertUser
    {
        Task DisplayAlertAsync(string title, string message, string cancel = "Dismiss", AlertType alertType = AlertType.FailureAlert);

    }

    public sealed class HandleExceptionAttribute : OverrideMethodAspect
    {
        private string _title;
        private string _message;
        private bool _unexpected;

        public HandleExceptionAttribute(string title, string message)
        {
            _title = title;
            _message = message;
        }

        public override dynamic? OverrideMethod()
        {
            throw new NotImplementedException("Exception handling only for async methods");
        }

        public override async Task<dynamic?> OverrideAsyncMethod()
        {
            try
            {
                return await meta.ProceedAsync();
            }
            catch (Exception ex)
            {
                if (meta.This is IAlertUser alertUser)
                    await alertUser.DisplayAlertAsync(_title, _message, alertType: AlertType.FailureAlert);

                // Swallow the exception
                return null;
            }
        }
    }
}
```
4. Added the following class to the console project:
```
using ServicePlatform.Aspects;

namespace TestMeta
{

    internal class Divider : IAlertUser
    {
        public async Task DisplayAlertAsync(string title, string message, string cancel = "Dismiss", AlertType alertType = AlertType.FailureAlert)
        {
            Console.WriteLine($"{title}: {message}");
        }

        [HandleException("A strange thing happened", "Check your parameters maybe")]
        public async Task<int?> DoSomethingStrange(int numerator, int denominator) {
            return numerator / denominator;
        }
    }
}
```
5. I updated the Program.cs file to: 
```
TestMeta.Divider divider = new TestMeta.Divider();

int? result = await divider.DoSomethingStrange(9, 3);
Console.WriteLine($" 9 / 3 = {result}");

result = await divider.DoSomethingStrange(9, 0);
Console.WriteLine($" 9 / 0 = {result}");
```

The library project builds correctly but when the console project is built it produces the error:
`error CS4032: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task<Task<int?>>`

If I use metalama diff I get the expected code and if I replace the original with this and remove the aspect attribute then everything builds and runs.

```
        public async Task<int?> DoSomethingStrange(int numerator, int denominator) {
            try
            {
                return await this.DoSomethingStrange_Source(numerator, denominator);
            }
            catch (Exception ex)
            {
                if (this is IAlertUser alertUser)
                    await alertUser.DisplayAlertAsync("A strange thing happened", "Check your parameters maybe", alertType: AlertType.FailureAlert);
                return null;
            }
        }

        private async Task<int?> DoSomethingStrange_Source(int numerator, int denominator)
        {
            return numerator / denominator;
        }
    }
```

**Comment by addabis** [comment]
I have managed to reproduce the problem, it happens in the case of an aspect declared in another assembly and specifically with async templates. I have filed a bug for this.
 
I have also seen that you are using "return null;" in your template, which causes invalid code to be generated when applied to value-type returning methods. I would suggest using "return default;" instead. At this point, Metalama is not able to provide a user-friendly error for this during template expansion.

**Comment by addabis** [comment]
I have managed to reproduce the problem, it happens in the case of an aspect declared in another assembly and specifically with async templates. I have filed a bug for this.

I have also seen that you are using "return null;" in your template, which causes invalid code to be generated when applied to value-type returning methods. I would suggest using "return default;" instead. At this point, Metalama is not able to provide a user-friendly error for this during template expansion.

**Comment by prochan2** [comment]
Running the example online in [Try Metalama](https://try.metalama.net) is fixed now.

**Comment by SophisticatedConsulting** [comment]
Thanks @prochan2 for the quick turnaround. 
Do you have a date for the fix in a nuget release?
Much appreciated,
Vincent.

**Comment by prochan2** [comment]
We don't have an exact date yet, but the fix is planned along with other known issues. We'll let you know as soon as it's fixed.

**Comment by SophisticatedConsulting** [comment]
Please would you prioritise this. It is a blocker for MAUI/.NET 6.0 migration.
This would presumably apply to any other customers wishing to migrate to or build apps in .NET 6 as the requirement to use Rosalyn is that metalama must be run in a Net Standard 2.1 library, i.e. aspects must be defined in an external library.
Note that the issue was raised 1 month ago.
Much appreciated.

**Comment by prochan2** [comment]
Hi @SophisticatedConsulting, we've had some other important bugs to fix in the queue, but this one is just about to be fixed these days.

**Comment by aweneer** [comment]
Hello @SophisticatedConsulting, we have fixed this bug in the current Metalama release 0.5.24-preview.
