### ISSUE TITLE
Can not introduce partial method

### ISSUE THREAD

**Issue by yumikou** [postsharp/Metalama#33]
Hi!
I want to introduce a partial method for class.
Like this:
```
[MD(Name = "Custom")]
public partial class TestClass
{
    partial void OnCustomChanged(int i);
}
```
This is my attribute:
```
public partial class MDAttribute : TypeAspect
{
    public string Name { get; set; }

    public override void BuildAspect(IAspectBuilder<INamedType> builder)
    {
        builder.Advice.IntroduceMethod(
                builder.Target,
                nameof(MDAttribute.NameChangedTemplate),
                buildMethod: m =>
                {
                    m.Name = $"On{Name}Changed";
                }
                );
    }

    [Template]
    partial void NameChangedTemplate(int i);
}
```
then  I get the following error:
```
Metalama Version: 0.5.34-preview
Runtime: .NET Framework 4.8.4400.0
Processor Architecture: X64
OS Description: Microsoft Windows 10.0.19043 
OS Architecture: X64
Exception type: Metalama.Framework.Engine.AssertionFailedException
Exception message: Could not find the compile template for MDAttribute.NameChangedTemplate(int).
===== Exception ===== 
Metalama.Framework.Engine.AssertionFailedException: Could not find the compile template for MDAttribute.NameChangedTemplate(int).
   at Metalama.Framework.Engine.Aspects.TemplateClass.^SDhMwYFx(IMember _0)
   at Obfuscated.^sAYH7wxTVE7N.^o0m7xoS_(^bLKSlKcY22U3& _0)
   at Obfuscated.^RB4kYY0pN6FB.^QPxfaziD(^_XL_Cszqd2Vh _0, List`1 _1, UserDiagnosticSink _2, ^eVHnT5Ga_VC8 _3, ^zxpT_mWhoKQE _4, ^Y82ONgmzqAto _5, IReadOnlyCollection`1 _6, ^oTFIQzj4 _7, HashSet`1 _8)
   at Obfuscated.^RB4kYY0pN6FB.^46Z9(^_XL_Cszqd2Vh _0)
   at Obfuscated.^XvFgQf6vvYK8.^28tIpU9F()
   at Obfuscated.^gzIzh9UP0pDC.^4Vg2G3mY(AspectPipelineConfiguration _0, AspectPipelineResult _1, ^mCAaZZ8k632t _2, CancellationToken _3)
   at Obfuscated.^mjGX9Ib2unuR.^_w6byyh5(AspectPipelineConfiguration _0, AspectPipelineResult _1, IDiagnosticAdder _2, CancellationToken _3, AspectPipelineResult& _4)
   at Metalama.Framework.Engine.Pipeline.AspectPipeline.^_w6byyh5(PartialCompilation _0, CompilationModel _1, IDiagnosticAdder _2, AspectPipelineConfiguration _3, CancellationToken _4, AspectPipelineResult& _5)
   at Metalama.Framework.Engine.Pipeline.CompileTime.CompileTimeAspectPipeline.^UcvoxiWP.^0NTn5_wx()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Metalama.Framework.Engine.Pipeline.CompileTime.CompileTimeAspectPipeline.^4m1nNkaa.^0NTn5_wx()
```

**Comment by gfraiteur** [comment]
This is not supported. I have filed a bug to report a better error message.

What is your use case? I don't understand when it should be useful.

**Comment by yumikou** [comment]
> This is not supported. I have filed a bug to report a better error message.
> 
> What is your use case? I don't understand when it should be useful.

This is really not a common use case. 

Look at this generated code:
```
[DependencyProperty(Name = "Custom", Type = typeof(string), IsChanged = true)]
public partial class TestClass : DependencyObject
{
    public string Custom
    {
        get => (string)this.GetValue(CustomProperty);
        set => this.SetValue(CustomProperty, value);
    }

    public static readonly DependencyProperty CustomProperty
        = DependencyProperty.Register(nameof(Custom),
                                        typeof(string),
                                        typeof(TestClass),
                                        new PropertyMetadata(
                                            default(string),
                                            OnCustomPropertyChanged
                                        ));
    static partial void OnCustomPropertyChanged(DependencyObject sender, DependencyPropertyChangedEventArgs e);
}
```
If there is a partial method in the class,  I just need to enter "partial", it will helps me to quickly enter a method signature while writing code by IntelliSense.

This feature is not particularly important to me, if you have no plan for this, you can close this issue.

**Comment by prochan2** [comment]
I have created an idea for this feature at https://support.postsharp.net/request/30934-introduction-of-partial-methods , so we can consider it. But most probably, it will not make it to the first RTM of Metalama.

**Comment by YBAZAN** [comment]
Hi, is this feature planned to be implemented?
I have the same need than @prochan2 in order to get rid off other source generators (it's for XAML project)

**Comment by gfraiteur** [comment]
No, we haven't scheduled that feature yet.

**Comment by gfraiteur** [comment]
In  2023.0.102-rc, a better error message will be reported.
