### ISSUE TITLE
Exception with "Cannot get the namespace of a type that is not a part of the current compilation."

### ISSUE THREAD

**Issue by batzen** [postsharp/Metalama#37]
Hi there.

I am getting an exception with the message "Cannot get the namespace of a type that is not a part of the current compilation.".

I have a project containing my aspects and a project referencing the project containing the aspects.
The aspects work fine in the project containing them, but when trying to compile the project referencing the other one i get said exception.

Both projects reference MetaLama.Framework.

```
Metalama Version: 0.5.36-preview
Runtime: .NET 6.0.7
Processor Architecture: X64
OS Description: Microsoft Windows 10.0.19042
OS Architecture: X64
Exception type: System.InvalidOperationException
Exception message: Cannot get the namespace of a type that is not a part of the current compilation.
===== Exception ===== 
System.InvalidOperationException: Cannot get the namespace of a type that is not a part of the current compilation.
   at Metalama.Framework.Engine.CodeModel.DeclarationFactory.^FjYR9gPH(INamespaceSymbol _0)
   at Obfuscated.^f4UvEa7FyDPu.get_Namespace()
   at Metalama.Framework.Engine.CodeModel.CompilationModel.^1_XtzBd3(INamedType _0)
   at Metalama.Framework.Engine.CodeModel.CompilationModel.^1_XtzBd3(IDeclaration _0)
   at Obfuscated.^JPhCEiV5epPJ.^ckFJx49g(IEnumerable`1 _0)
   at Obfuscated.^uGJYB_0LOn4y.^46Z9(CompilationModel _0, CancellationToken _1)
   at Obfuscated.^JPhCEiV5epPJ.^46Z9(CancellationToken _0)
   at Obfuscated.^mjGX9Ib2unuR.^_w6byyh5(AspectPipelineConfiguration _0, AspectPipelineResult _1, IDiagnosticAdder _2, CancellationToken _3, AspectPipelineResult& _4)
   at Metalama.Framework.Engine.Pipeline.AspectPipeline.^_w6byyh5(PartialCompilation _0, CompilationModel _1, IDiagnosticAdder _2, AspectPipelineConfiguration _3, CancellationToken _4, AspectPipelineResult& _5)
   at Metalama.Framework.Engine.Pipeline.CompileTime.CompileTimeAspectPipeline.ExecuteCoreAsync(IDiagnosticAdder diagnosticAdder, PartialCompilation compilation, ImmutableArray`1 resources, AspectPipelineConfiguration configuration, CancellationToken cancellationToken)
   at Metalama.Framework.Engine.Pipeline.CompileTime.CompileTimeAspectPipeline.ExecuteAsync(IDiagnosticAdder diagnosticAdder, Compilation compilation, ImmutableArray`1 resources, CancellationToken cancellationToken)
```

**Comment by batzen** [comment]
What does "that is not part of the current compilation" mean exactly?

My fabrics all look like this:
```
internal class ObjectNotNullRequiredAttributeFabric : ProjectFabric
{
    public override void AmendProject(IProjectAmender project )
    {
        project.With(p => p.Types.Where(x => x.IsAbstract == false).SelectMany(x => x.Methods)
            .Where(x => ObjectNotNullRequiredAttribute.IsNullCheckRequired(x)))
            .AddAspect<ObjectNotNullRequiredAttribute>();
    }
}
```

**Comment by prochan2** [comment]
It could mean a type from a referenced assembly.

I found a bug in our backlog, that presents itself the same way: https://support.postsharp.net/request/30621-exception-thrown-when-applying-an-aspect

The relevant comment is:

> Ok, I figured out and now know why it didn't work on simple example.
>
> There needs to be at least two inheriting classes. So, to summary:
>
> Core project references Metalama, contains aspect and class (A) that uses it and another class (B) that inherits from A.
> Presentation project references Core and contains class (C) that inherits from (B). The exception is thrown from Presentation project
>
> When I remove class B and class C inherits directly from class A, it compiles.

Could it be the same case for you?

**Comment by batzen** [comment]
That was also the case for my test project, yes.
After changing the class hierarchy from `BaseClass -> Inherited -> InheritedInOtherProject` to `BaseClass -> 
 InheritedInOtherProject` i don't get the namespace exception.

**Comment by prochan2** [comment]
Thank you for the confirmation. We'll let you know as soon as this bug has been fixed.

**Comment by batzen** [comment]
Tested with 0.5.47-preview i now get "Cannot compute the depth of 'MetaTest.Inherited' because it is an external type." instead.

**Comment by gfraiteur** [comment]
Can you check with 0.5.48-preview? I may have been confused and wrote that the issue was fixed where it was actually not released. Thank you.

**Comment by batzen** [comment]
Works with 0.5.48.
Thanks for fixing it.
